package HelloNaming;


/**
* HelloNaming/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorldName.idl
* 26 February 2015 09:25:27 o'clock GMT
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
