package HelloNaming;


/**
* HelloNaming/HelloPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorldName.idl
* 26 February 2015 09:25:27 o'clock GMT
*/

public class HelloPOATie extends HelloPOA
{

  // Constructors

  public HelloPOATie ( HelloNaming.HelloOperations delegate ) {
      this._impl = delegate;
  }
  public HelloPOATie ( HelloNaming.HelloOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public HelloNaming.HelloOperations _delegate() {
      return this._impl;
  }
  public void _delegate (HelloNaming.HelloOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public String sayHello ()
  {
    return _impl.sayHello();
  } // sayHello

  private HelloNaming.HelloOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class HelloPOATie
