package DateApp;


/**
* DateApp/DateInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Date.idl
* Tuesday, January 27, 2015 11:49:28 AM GMT
*/

public interface DateInterfaceOperations 
{
  String getMasterDateMethod (String student);
} // interface DateInterfaceOperations
