package DateApp;


/**
* DateApp/DateInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Date.idl
* Tuesday, January 27, 2015 11:49:28 AM GMT
*/

public interface DateInterface extends DateInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DateInterface
