package HelloDeferredSynchronous;


/**
* HelloDeferredSynchronous/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorldDeferredSynchronous.idl
* 11 March 2015 20:33:29 o'clock GMT
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
