package HelloDeferredSynchronous;

/**
* HelloDeferredSynchronous/HelloHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorldDeferredSynchronous.idl
* 11 March 2015 20:33:29 o'clock GMT
*/

public final class HelloHolder implements org.omg.CORBA.portable.Streamable
{
  public HelloDeferredSynchronous.Hello value = null;

  public HelloHolder ()
  {
  }

  public HelloHolder (HelloDeferredSynchronous.Hello initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloDeferredSynchronous.HelloHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloDeferredSynchronous.HelloHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloDeferredSynchronous.HelloHelper.type ();
  }

}
