package HelloDeferredSynchronous;


/**
* HelloDeferredSynchronous/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorldDeferredSynchronous.idl
* 11 March 2015 20:33:29 o'clock GMT
*/

public interface HelloOperations 
{

  //3 for Dublin
  String sayHello (int audience);
} // interface HelloOperations
