package HelloDeferredSynchronous;


/**
* HelloDeferredSynchronous/Hello_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorldDeferredSynchronous.idl
* 11 March 2015 20:33:29 o'clock GMT
*/

public class Hello_Tie extends _HelloImplBase
{

  // Constructors
  public Hello_Tie ()
  {
  }

  public Hello_Tie (HelloDeferredSynchronous.HelloOperations impl)
  {
    super ();
    _impl = impl;
  }


  //3 for Dublin
  public String sayHello (int audience)
  {
    return _impl.sayHello(audience);
  } // sayHello

  private HelloDeferredSynchronous.HelloOperations _impl;

} // class Hello_Tie
