package HelloWorldTieApp;


/**
* HelloWorldTieApp/HelloWorldInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorldTie.idl
* 09 February 2015 13:37:29 o'clock GMT
*/

public interface HelloWorldInterfaceOperations 
{
  String sayHelloMethod ();
} // interface HelloWorldInterfaceOperations
