package HelloWorldTieApp;


/**
* HelloWorldTieApp/HelloWorldInterface_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorldTie.idl
* 09 February 2015 13:37:29 o'clock GMT
*/

public class HelloWorldInterface_Tie extends _HelloWorldInterfaceImplBase
{

  // Constructors
  public HelloWorldInterface_Tie ()
  {
  }

  public HelloWorldInterface_Tie (HelloWorldTieApp.HelloWorldInterfaceOperations impl)
  {
    super ();
    _impl = impl;
  }

  public String sayHelloMethod ()
  {
    return _impl.sayHelloMethod();
  } // sayHelloMethod

  private HelloWorldTieApp.HelloWorldInterfaceOperations _impl;

} // class HelloWorldInterface_Tie
