package HelloWorldTieApp;


/**
* HelloWorldTieApp/HelloWorldInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorldTie.idl
* 09 February 2015 13:37:29 o'clock GMT
*/

public interface HelloWorldInterface extends HelloWorldInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface HelloWorldInterface
