package HelloOneway;


/**
* HelloOneway/Hello_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloOneway.idl
* 11 March 2015 20:21:45 o'clock GMT
*/

public class Hello_Tie extends _HelloImplBase
{

  // Constructors
  public Hello_Tie ()
  {
  }

  public Hello_Tie (HelloOneway.HelloOperations impl)
  {
    super ();
    _impl = impl;
  }


  //3 for Dublin
  public void sayHello (int audience)
  {
    _impl.sayHello(audience);
  } // sayHello

  private HelloOneway.HelloOperations _impl;

} // class Hello_Tie
