package HelloOneway;


/**
* HelloOneway/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloOneway.idl
* 11 March 2015 20:21:45 o'clock GMT
*/

public interface HelloOperations 
{

  //3 for Dublin
  void sayHello (int audience);
} // interface HelloOperations
