package HelloOneway;


/**
* HelloOneway/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloOneway.idl
* 11 March 2015 20:21:45 o'clock GMT
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
