package HelloOneway;

/**
* HelloOneway/HelloHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloOneway.idl
* 11 March 2015 20:21:45 o'clock GMT
*/

public final class HelloHolder implements org.omg.CORBA.portable.Streamable
{
  public HelloOneway.Hello value = null;

  public HelloHolder ()
  {
  }

  public HelloHolder (HelloOneway.Hello initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloOneway.HelloHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloOneway.HelloHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloOneway.HelloHelper.type ();
  }

}
