package DateApp;


/**
* DateApp/DateInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Date.idl
* Wednesday, January 28, 2015 6:00:41 PM GMT
*/

public interface DateInterface extends DateInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DateInterface
