package DateApp;


/**
* DateApp/DateInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Date.idl
* Wednesday, January 28, 2015 6:00:41 PM GMT
*/

public interface DateInterfaceOperations 
{
  String getDateMethod ();
} // interface DateInterfaceOperations
