package GridWorld;


/**
* GridWorld/GridPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from grid.idl
* 11 March 2015 21:23:05 o'clock GMT
*/

public class GridPOATie extends GridPOA
{

  // Constructors

  public GridPOATie ( GridWorld.GridOperations delegate ) {
      this._impl = delegate;
  }
  public GridPOATie ( GridWorld.GridOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public GridWorld.GridOperations _delegate() {
      return this._impl;
  }
  public void _delegate (GridWorld.GridOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public int rows ()
  {
    return _impl.rows();
  } // rows

  public int columns ()
  {
    return _impl.columns();
  } // columns

  public void set (int row, int column, int value)
  {
    _impl.set(row, column, value);
  } // set

  public int get (int row, int column)
  {
    return _impl.get(row, column);
  } // get

  private GridWorld.GridOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class GridPOATie
