package GridWorld;


/**
* GridWorld/GridOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from grid.idl
* 11 March 2015 21:23:05 o'clock GMT
*/

public interface GridOperations 
{
  int rows ();
  int columns ();
  void set (int row, int column, int value);
  int get (int row, int column);
} // interface GridOperations
