package GridWorld;


/**
* GridWorld/GridPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from grid.idl
* 11 March 2015 21:23:05 o'clock GMT
*/

public abstract class GridPOA extends org.omg.PortableServer.Servant
 implements GridWorld.GridOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_rows", new java.lang.Integer (0));
    _methods.put ("_get_columns", new java.lang.Integer (1));
    _methods.put ("set", new java.lang.Integer (2));
    _methods.put ("get", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // GridWorld/Grid/_get_rows
       {
         int $result = (int)0;
         $result = this.rows ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // GridWorld/Grid/_get_columns
       {
         int $result = (int)0;
         $result = this.columns ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // GridWorld/Grid/set
       {
         int row = in.read_long ();
         int column = in.read_long ();
         int value = in.read_long ();
         this.set (row, column, value);
         out = $rh.createReply();
         break;
       }

       case 3:  // GridWorld/Grid/get
       {
         int row = in.read_long ();
         int column = in.read_long ();
         int $result = (int)0;
         $result = this.get (row, column);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:GridWorld/Grid:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Grid _this() 
  {
    return GridHelper.narrow(
    super._this_object());
  }

  public Grid _this(org.omg.CORBA.ORB orb) 
  {
    return GridHelper.narrow(
    super._this_object(orb));
  }


} // class GridPOA
