package GridWorld;


/**
* GridWorld/GridHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from grid.idl
* 11 March 2015 21:23:05 o'clock GMT
*/

abstract public class GridHelper
{
  private static String  _id = "IDL:GridWorld/Grid:1.0";

  public static void insert (org.omg.CORBA.Any a, GridWorld.Grid that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static GridWorld.Grid extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (GridWorld.GridHelper.id (), "Grid");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static GridWorld.Grid read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GridStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, GridWorld.Grid value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static GridWorld.Grid narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof GridWorld.Grid)
      return (GridWorld.Grid)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      GridWorld._GridStub stub = new GridWorld._GridStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static GridWorld.Grid unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof GridWorld.Grid)
      return (GridWorld.Grid)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      GridWorld._GridStub stub = new GridWorld._GridStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
