package GridWorld;


/**
* GridWorld/Grid.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from grid.idl
* 11 March 2015 21:23:05 o'clock GMT
*/

public interface Grid extends GridOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Grid
