package HelloDynamicInvocation;


/**
* HelloDynamicInvocation/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorldDynamicInvocation.idl
* 11 March 2015 14:39:43 o'clock GMT
*/

public interface HelloOperations 
{

  //3 for Dublin
  String sayHello (int audience);
} // interface HelloOperations
