package HelloDynamicInvocation;


/**
* HelloDynamicInvocation/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorldDynamicInvocation.idl
* 11 March 2015 14:39:43 o'clock GMT
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
