package HelloDynamicInvocation;


/**
* HelloDynamicInvocation/Hello_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorldDynamicInvocation.idl
* 11 March 2015 14:39:43 o'clock GMT
*/

public class Hello_Tie extends _HelloImplBase
{

  // Constructors
  public Hello_Tie ()
  {
  }

  public Hello_Tie (HelloDynamicInvocation.HelloOperations impl)
  {
    super ();
    _impl = impl;
  }


  //3 for Dublin
  public String sayHello (int audience)
  {
    return _impl.sayHello(audience);
  } // sayHello

  private HelloDynamicInvocation.HelloOperations _impl;

} // class Hello_Tie
