package AnyExample;


/**
* AnyExample/_TimeOfDayImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Time.idl
* 11 March 2015 14:22:55 o'clock GMT
*/

public abstract class _TimeOfDayImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements AnyExample.TimeOfDay, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _TimeOfDayImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("hello", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // AnyExample/TimeOfDay/hello
       {
         org.omg.CORBA.AnyHolder anyTime = new org.omg.CORBA.AnyHolder ();
         org.omg.CORBA.Any $result = null;
         $result = this.hello (anyTime);
         out = $rh.createReply();
         out.write_any ($result);
         out.write_any (anyTime.value);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:AnyExample/TimeOfDay:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _TimeOfDayImplBase
