package AnyExample;

/**
* AnyExample/TimeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Time.idl
* 11 March 2015 14:22:55 o'clock GMT
*/

public final class TimeHolder implements org.omg.CORBA.portable.Streamable
{
  public AnyExample.Time value = null;

  public TimeHolder ()
  {
  }

  public TimeHolder (AnyExample.Time initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AnyExample.TimeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AnyExample.TimeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AnyExample.TimeHelper.type ();
  }

}
