package AnyExample;


/**
* AnyExample/TimeOfDay.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Time.idl
* 11 March 2015 14:22:55 o'clock GMT
*/

public interface TimeOfDay extends TimeOfDayOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface TimeOfDay
