package AnyExample;


/**
* AnyExample/Time.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Time.idl
* 11 March 2015 14:22:55 o'clock GMT
*/

public final class Time implements org.omg.CORBA.portable.IDLEntity
{
  public int hour = (int)0;
  public int minute = (int)0;

  public Time ()
  {
  } // ctor

  public Time (int _hour, int _minute)
  {
    hour = _hour;
    minute = _minute;
  } // ctor

} // class Time
