package AnyExample;


/**
* AnyExample/TimeOfDayOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Time.idl
* 11 March 2015 14:22:55 o'clock GMT
*/

public interface TimeOfDayOperations 
{
  org.omg.CORBA.Any hello (org.omg.CORBA.AnyHolder anyTime);
} // interface TimeOfDayOperations
