package AnyExample;

/**
* AnyExample/TimeOfDayHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Time.idl
* 11 March 2015 14:22:55 o'clock GMT
*/

public final class TimeOfDayHolder implements org.omg.CORBA.portable.Streamable
{
  public AnyExample.TimeOfDay value = null;

  public TimeOfDayHolder ()
  {
  }

  public TimeOfDayHolder (AnyExample.TimeOfDay initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AnyExample.TimeOfDayHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AnyExample.TimeOfDayHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AnyExample.TimeOfDayHelper.type ();
  }

}
