package AnyExample;


/**
* AnyExample/TimeOfDayHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Time.idl
* 11 March 2015 14:22:55 o'clock GMT
*/

abstract public class TimeOfDayHelper
{
  private static String  _id = "IDL:AnyExample/TimeOfDay:1.0";

  public static void insert (org.omg.CORBA.Any a, AnyExample.TimeOfDay that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static AnyExample.TimeOfDay extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (AnyExample.TimeOfDayHelper.id (), "TimeOfDay");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static AnyExample.TimeOfDay read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_TimeOfDayStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, AnyExample.TimeOfDay value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static AnyExample.TimeOfDay narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof AnyExample.TimeOfDay)
      return (AnyExample.TimeOfDay)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      AnyExample._TimeOfDayStub stub = new AnyExample._TimeOfDayStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static AnyExample.TimeOfDay unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof AnyExample.TimeOfDay)
      return (AnyExample.TimeOfDay)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      AnyExample._TimeOfDayStub stub = new AnyExample._TimeOfDayStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
