package AnyExample;


/**
* AnyExample/TimeOfDay_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Time.idl
* 11 March 2015 14:22:55 o'clock GMT
*/

public class TimeOfDay_Tie extends _TimeOfDayImplBase
{

  // Constructors
  public TimeOfDay_Tie ()
  {
  }

  public TimeOfDay_Tie (AnyExample.TimeOfDayOperations impl)
  {
    super ();
    _impl = impl;
  }

  public org.omg.CORBA.Any hello (org.omg.CORBA.AnyHolder anyTime)
  {
    return _impl.hello(anyTime);
  } // hello

  private AnyExample.TimeOfDayOperations _impl;

} // class TimeOfDay_Tie
