package HelloNaming;


/**
* HelloNaming/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/I306184/Desktop/DS lab 3b/0_HelloNaming_LectureExample/HelloNaming.idl
* 18 February 2015 21:44:59 o'clock GMT
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
