package HelloNaming;


/**
* HelloNaming/Hello_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/I306184/Desktop/DS lab 3b/0_HelloNaming_LectureExample/HelloNaming.idl
* 18 February 2015 21:44:59 o'clock GMT
*/

public class Hello_Tie extends _HelloImplBase
{

  // Constructors
  public Hello_Tie ()
  {
  }

  public Hello_Tie (HelloNaming.HelloOperations impl)
  {
    super ();
    _impl = impl;
  }

  public String sayHello ()
  {
    return _impl.sayHello();
  } // sayHello

  private HelloNaming.HelloOperations _impl;

} // class Hello_Tie
