package HelloNaming;


/**
* HelloNaming/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorldName.idl
* Tuesday, January 27, 2015 9:57:19 PM GMT
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
