package onLineBanking;


/**
* onLineBanking/_OnLineBankingStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OnLineBanking.idl
* 11 March 2015 20:55:17 o'clock GMT
*/

public class _OnLineBankingStub extends org.omg.CORBA.portable.ObjectImpl implements onLineBanking.OnLineBanking
{

  public void registerOnLineBanking (org.omg.CORBA.Any anyOnLineDetails, org.omg.CORBA.StringHolder password)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registerOnLineBanking", true);
                $out.write_any (anyOnLineDetails);
                $in = _invoke ($out);
                password.value = $in.read_string ();
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                registerOnLineBanking (anyOnLineDetails, password        );
            } finally {
                _releaseReply ($in);
            }
  } // registerOnLineBanking

  public void performOnLineTransaction (String UniqueID, int amount, org.omg.CORBA.AnyHolder anyOnLineDetails)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("performOnLineTransaction", true);
                $out.write_string (UniqueID);
                $out.write_long (amount);
                $in = _invoke ($out);
                anyOnLineDetails.value = $in.read_any ();
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                performOnLineTransaction (UniqueID, amount, anyOnLineDetails        );
            } finally {
                _releaseReply ($in);
            }
  } // performOnLineTransaction

  public onLineBanking.onLineDetails getAccountInfo (String UniqueID)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getAccountInfo", true);
                $out.write_string (UniqueID);
                $in = _invoke ($out);
                onLineBanking.onLineDetails $result = onLineBanking.onLineDetailsHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getAccountInfo (UniqueID        );
            } finally {
                _releaseReply ($in);
            }
  } // getAccountInfo

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:onLineBanking/OnLineBanking:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _OnLineBankingStub
