package onLineBanking;

/**
* onLineBanking/OnLineBankingHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OnLineBanking.idl
* 11 March 2015 20:55:17 o'clock GMT
*/

public final class OnLineBankingHolder implements org.omg.CORBA.portable.Streamable
{
  public onLineBanking.OnLineBanking value = null;

  public OnLineBankingHolder ()
  {
  }

  public OnLineBankingHolder (onLineBanking.OnLineBanking initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = onLineBanking.OnLineBankingHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    onLineBanking.OnLineBankingHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return onLineBanking.OnLineBankingHelper.type ();
  }

}
