package onLineBanking;

/**
* onLineBanking/onLineDetailsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OnLineBanking.idl
* 11 March 2015 20:55:17 o'clock GMT
*/

public final class onLineDetailsHolder implements org.omg.CORBA.portable.Streamable
{
  public onLineBanking.onLineDetails value = null;

  public onLineDetailsHolder ()
  {
  }

  public onLineDetailsHolder (onLineBanking.onLineDetails initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = onLineBanking.onLineDetailsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    onLineBanking.onLineDetailsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return onLineBanking.onLineDetailsHelper.type ();
  }

}
