package onLineBanking;


/**
* onLineBanking/OnLineBanking.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OnLineBanking.idl
* 11 March 2015 20:55:17 o'clock GMT
*/

public interface OnLineBanking extends OnLineBankingOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface OnLineBanking
