package onLineBanking;


/**
* onLineBanking/OnLineBankingOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OnLineBanking.idl
* 11 March 2015 20:55:17 o'clock GMT
*/

public interface OnLineBankingOperations 
{
  void registerOnLineBanking (org.omg.CORBA.Any anyOnLineDetails, org.omg.CORBA.StringHolder password);
  void performOnLineTransaction (String UniqueID, int amount, org.omg.CORBA.AnyHolder anyOnLineDetails);
  onLineBanking.onLineDetails getAccountInfo (String UniqueID);
} // interface OnLineBankingOperations
