package AddressBookAny;


/**
* AddressBookAny/_distAddrBkImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AB.idl
* 11 March 2015 14:48:56 o'clock GMT
*/

public abstract class _distAddrBkImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements AddressBookAny.distAddrBk, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _distAddrBkImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("storePhoneBookDetails", new java.lang.Integer (0));
    _methods.put ("getPhoneBookDetails", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // AddressBookAny/distAddrBk/storePhoneBookDetails
       {
         AddressBookAny.AddressBook myAddressBook = AddressBookAny.AddressBookHelper.read (in);
         this.storePhoneBookDetails (myAddressBook);
         out = $rh.createReply();
         break;
       }

       case 1:  // AddressBookAny/distAddrBk/getPhoneBookDetails
       {
         String name = in.read_string ();
         org.omg.CORBA.AnyHolder myAddressBook = new org.omg.CORBA.AnyHolder ();
         this.getPhoneBookDetails (name, myAddressBook);
         out = $rh.createReply();
         out.write_any (myAddressBook.value);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:AddressBookAny/distAddrBk:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _distAddrBkImplBase
