package AddressBookAny;

/**
* AddressBookAny/AddressBookHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AB.idl
* 11 March 2015 14:48:56 o'clock GMT
*/

public final class AddressBookHolder implements org.omg.CORBA.portable.Streamable
{
  public AddressBookAny.AddressBook value = null;

  public AddressBookHolder ()
  {
  }

  public AddressBookHolder (AddressBookAny.AddressBook initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AddressBookAny.AddressBookHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AddressBookAny.AddressBookHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AddressBookAny.AddressBookHelper.type ();
  }

}
