package AddressBookAny;


/**
* AddressBookAny/AddressBook.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AB.idl
* 11 March 2015 14:48:56 o'clock GMT
*/

public final class AddressBook implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String address = null;
  public String phone = null;
  public String email = null;

  public AddressBook ()
  {
  } // ctor

  public AddressBook (String _name, String _address, String _phone, String _email)
  {
    name = _name;
    address = _address;
    phone = _phone;
    email = _email;
  } // ctor

} // class AddressBook
