package AddressBookAny;


/**
* AddressBookAny/distAddrBkOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AB.idl
* 11 March 2015 14:48:56 o'clock GMT
*/

public interface distAddrBkOperations 
{
  void storePhoneBookDetails (AddressBookAny.AddressBook myAddressBook);
  void getPhoneBookDetails (String name, org.omg.CORBA.AnyHolder myAddressBook);
} // interface distAddrBkOperations
