package AddressBookAny;


/**
* AddressBookAny/distAddrBk.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AB.idl
* 11 March 2015 14:48:56 o'clock GMT
*/

public interface distAddrBk extends distAddrBkOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface distAddrBk
