package AddressBookAny;

/**
* AddressBookAny/distAddrBkHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AB.idl
* 11 March 2015 14:48:56 o'clock GMT
*/

public final class distAddrBkHolder implements org.omg.CORBA.portable.Streamable
{
  public AddressBookAny.distAddrBk value = null;

  public distAddrBkHolder ()
  {
  }

  public distAddrBkHolder (AddressBookAny.distAddrBk initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AddressBookAny.distAddrBkHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AddressBookAny.distAddrBkHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AddressBookAny.distAddrBkHelper.type ();
  }

}
