package AddressBookAny;


/**
* AddressBookAny/distAddrBk_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AB.idl
* 11 March 2015 14:48:56 o'clock GMT
*/

public class distAddrBk_Tie extends _distAddrBkImplBase
{

  // Constructors
  public distAddrBk_Tie ()
  {
  }

  public distAddrBk_Tie (AddressBookAny.distAddrBkOperations impl)
  {
    super ();
    _impl = impl;
  }

  public void storePhoneBookDetails (AddressBookAny.AddressBook myAddressBook)
  {
    _impl.storePhoneBookDetails(myAddressBook);
  } // storePhoneBookDetails

  public void getPhoneBookDetails (String name, org.omg.CORBA.AnyHolder myAddressBook)
  {
    _impl.getPhoneBookDetails(name, myAddressBook);
  } // getPhoneBookDetails

  private AddressBookAny.distAddrBkOperations _impl;

} // class distAddrBk_Tie
